# Generated by Django 5.0.3 on 2024-12-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_id', models.TextField()),
                ('name', models.TextField()),
                ('ath_name', models.TextField()),
                ('bk_genres', models.TextField()),
                ('price', models.IntegerField()),
                ('ofr_price', models.IntegerField()),
                ('img', models.FileField(upload_to='')),
                ('dis', models.TextField()),
            ],
        ),
    ]
