# Generated by Django 5.0.3 on 2024-12-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='stock',
            field=models.IntegerField(default='20'),
            preserve_default=False,
        ),
    ]
